<!-- Standard trailer begins -->

<p class="lastmod">
<i>Last modified:
<?php
$filedate = filectime ('news.inc');
$datemodified = date("d M Y g:i A", $filedate);
echo $datemodified;
?> by Dominique Michel</i>
</i>
<br>
<br>This website and all its content is Copyright (C) 2013-2025 of their respective authors
<br>This webstie and all its content comes with ABSOLUTELY NO WARRANTY; for details see <a href="http://www.gnu.org/licenses/gpl-3.0.en.html">GNU GENERAL PUBLIC LICENSE Version 3</a>
<br>This is free software, and you are welcome to redistribute it under certain conditions; see <a href="http://www.gnu.org/licenses/gpl-3.0.en.html">GNU GENERAL PUBLIC LICENSE Version 3</a> for details.
<br><a href="https://alsaplayer.sourceforge.net">[Go back to home]</a>
</p>

</div>

</td>
</tr>
</table>
</body>
</html>
