<td>
<p><b>
Released version: <?php echo $latest_version; ?><br />
GIT version: <a href="https://www.github.com/alsaplayer/alsaplayer">latest</a><br />
</b></p>
<hr />
<ul>
	<li><a href="index.php?style=<?php echo $url; ?>">About / News</a></li>
	<li><a href="features.php?style=<?php echo $url; ?>">Features</a></li>
	<li><a href="screenshots.php?style=<?php echo $url; ?>">Screenshots</a></li>
	<li><a href="download.php?style=<?php echo $url; ?>">Download</a></li>
	<li><a href="git.php?style=<?php echo $url; ?>">GIT access</a></li>
	<li><a href="contribute.php?style=<?php echo $url; ?>">Contribute</a></li>
</ul>
<ul>
	<li><a href="artwork.php?style=<?php echo $url; ?>">Artwork</a></li>
</ul>
<ul>
	<li><a href="lists.php?style=<?php echo $url; ?>">Mailing lists</a></li>
	<li><a href="docs.php?style=<?php echo $url; ?>">Documentation</a></li>
	<li><a href="changelog.php?style=<?php echo $url; ?>">ChangeLog</a></li>
</ul>
<ul>
	<li><a href="action.php?style=<?php echo $url; ?>">Related projects</a></li>
	<li><a href="scopes.php?style=<?php echo $url; ?>">Outdated Scopes</a></li>
	<li><a href="ac3play.php?style=<?php echo $url; ?>">ac3play</a></li>
	<li><a href="attic.php?style=<?php echo $url; ?>">Attic</a></li>
</ul>
<ul>
	<li><a href="mailto:dominique_libre@users.sourceforge.net">Contact</a></li>
</ul>
<p>Style Switcher:
<ul id="styleswitcher">
  <li><a href="<?php echo $actuel; ?>?style=Dum">Dum style</a></li>
  <li><a href="<?php echo $actuel; ?>?style=Trinine">Trinine style</a></li>
  <li><a href="<?php echo $actuel; ?>?style=TrinineBW">Trinine b/W style</a></li>
  <li><a href="<?php echo $actuel; ?>?style=nostyle">No style</a></li>
</ul>
</p>
<p><b>Song of the week:<br /></b>
<b>Otyken - Chukotka (A whales and humans story)<br /></b>
<i>Title:</i> <a href="http://www.youtube.com/watch?v=PENk6NBEyPs&list=OLAK5uy_lqbt5qqM5wz6ZmXsZbvMMdfiQ8NzuHZNM&index=14">  Otyken - Chukotka</a><br />
</p>
<p id="centre">
<a href="http://sourceforge.net/projects/alsaplayer/"> 
<img src="http://sourceforge.net/sflogo.php?group_id=249" width="88" height="31" alt="SourceForge Logo" />
</a></p>
<br />
<br />
</td>

<td>
<!-- Main body -->
<div class="mainbody">
<!-- standard header ends -->

