<h2>News (Updated January 21, 2025)</h2>
<hr>
<dl>
<dt>
<dt>Development is occurring on github
<dd>See <a href="https://github.com/alsaplayer/alsaplayer">AlsaPlayer development</a>.
<hr>
<br>
<dt>September 12 2024
<dd>AlsaPlayer 0.99.82 is out.
<dd>It is mostly a huge rewrite of the core made by Erik de Castro Lopo in order to bump AlsaPlayer to modern audio coding standard.
<hr>
<br>
<dt>March 17 2013
<dd>Work in progress
<dd>I am working on the website those days. If you get some troubles with it, please refresh the page.
<hr>
<br>
<dt>March 16 2013
<dd>Better late than never! It is time for a new design for alsaplayer.org
<br>
<dd>I finally got some time to use the artworks. They was made in, well, 2007. I apologize for the delay.
<br>
<dd>The Dum style is based on artwork by Martin 'dum8d0g' Kopta.
<br>
<dd>The Trinine styles are based on artworks by Trinine (Tristan & Nini).
<br>
<dd>I also done a style without artwork and color. You can choose the style you want from the menu in the left column.
<br>
<dd>It will be very easy to incorporate new artworks and stykes, so feel free to contribute new artworks.
<hr>
<br>
<dt>December 2012
<dd>Erik de Castro Lopo joined AlsaPlayer
<br>
<dd>Erik de Castro Lopo joined the AlsaPlayer team. He is also called mega-nerd and is the main author and developper of libsndfile. He also have a nice website at <a href="http://www.mega-nerd.com/">mega-nerd.com</a>.
<br>
<dd>He allready begun to make hugue changes in the internals of alsaplayer. So, the next release will be a big step forward with a lot of improvments and bugfixes.
<br>
<dd>We also decided to shift from svn to git. The new code repository is located at <a href="https://github.com/alsaplayer/alsaplayer">alsaplayer on github</a>.
<hr>
<br>
<dt>November 7 2010
<dd>AlsaPlayer-0.99.81 is out,
<dd>This is a bug fix release.
<br>
<dd>A big thanks to all that send fixes to me, without you, the AlsaPlayer will not be living.
<br>
<dd>See the <a href="http://www.alsaplayer.org/changelog.php">ChangeLog</a> for the details and the names of the contributors.
<br>
<dd>I will also stress you to contribute to the AlsaPlayer. At least 2 things need to be fixed. The first one is the jack output plugin that is using deprecated functions. The second one is the resampling. For that, libsamplerate will give a better quality.
<br>
<dd>Enjoy the AlsaPlayer !
<hr>
<br>
<dt>November 3 2007
<dd>I am proud to announce that AlsaPlayer-0.99.80 got stable, thanks to the hard work of every one that contributed to the GTK2 interface and other functions as well that by submitting/fixing bugs.
<dd>This release is a bug fixes release. See the ChanLog for the details.<br>
<hr>
<br>
<dt>October 10 2007
<dd>AlsaPlayer 0.99.80-rc4 is out. This is a bug fixes and feature improvement release. Madej added a song title in the title bar option in the preferences. See the ChangeLog for details.<br>
<hr>
<br>
<dt>October 6 2007
<dd>AlsaPlayer 0.99.80-rc3 is out. This release include an important bug fix: the loading of the gtk2 config file is fixed (the gtk1 config file was loaded when present causing AP crash at start up).<br>
<dd>Every user is encouraged to upgrade.<br>
<dd>Other changes: Updated swedish translation, fix for possible buffer overflow in vorbis input plugin, updated man page.<br>
<hr>
<br>
<dt>September 25 2007
<dd>Take a look at the artwork page, it is some awesome works here. I made thumbnails, but the page can take a while to load on low bandwitch connection.<br>
<hr>
<br>
<dt>July 12 2007
<dd>AlsaPlayer 0.99.80-rc2 is out. The GTK2 get internationalization support with gettext.<br>
<dd>English, French, German, Polish and Swedish are included.<br>
<dd>The GTK1 interface get broken in the process and is removed from the package.<br>
<dd>Several bugs are fixed and the GTK2 interface get many improvements for a better user experience.<br>
<br>
<dd>AlsaPlayer license was updated to GPL-v3. In consequence, all the AlsaPlayer packages are updated with a new release.<br>
<dd>Every user is encouraged to upgrade AlsaPlayer and contribute with bugs reports, features requests and artworks contribution. (See the artwork page.)<br>
<dd>Translation for new languages will be very welcomed too.<br>
<hr>
<br>
<dt>June 13 2007
<dd>Just a warning. Don't press Enter on 0.99.80-rc1 or the application will crash. We didn't notice it before the release. It is fixed in the svn and will be included in 0.99.80-rc2.
<hr>
<br>
<dt>June 10 2007
<dd>GTK2 Interface
<dd>AlsaPlayer 0.99.80-rc1 is out. The player has now a fully working GTK2 interface.<br>
<dd>It includes the same functionality as the GTK1 interface and some new functions.<br>
<dd>The playlist window has been completely rewritten and is inside the main window.<br>
<dd>The scopes plugins have been migrated too.<br>
<dd>A lot of debugging has been made this last week.<br>
<br>
<dd>Every user is encouraged to upgrade AlsaPlayer and use the GTK2 interface.<br>
<br>
<dd> We need your help with a few things:<br>
<dd>* Bug reports<br>
<dd>* Feature requests<br>
<dd>* Artwork contributions<br>
<hr>
<br>
<dt>June 2 2007
<dd>A new release that will be a milestone is in preparation. It will include bug fixes and a very long wanted feature:<br>
<br>
<dd> - A full rewritted and nice working GTK2 interface.
<br>
<dd>That is not a first April joke! Hi, we are already in June! All begun when I get a mail from Madej from Poland with a patch for our favorite audio player.<br>
<dd>From that day, I am working with him on this interface, hum, it is actualy him that does most of the job.<br>
<dd>You can already get this code from the SVN page.<br>
<br>
<dt>Help needed
<dd>Look at the Artwork page. AlsaPlayer need a new logo and most of all, some nice looking icon.<br>
<dd>If you have some artwork to contribute, feel free to send them. The winner will win...<br>
<dd>Look at the Artwork page.<br>
<hr>
<br>
<dt>May 22, 2007
<dd>Alsaplayer 0.99.79 and fftscope 1.0.4 are out. This is a feature enhancement and minor bugfix release for Alsaplayer, a major bugfix release for fftsope.<br>
<br>
<dd>The new Alsaplayer features was first committed for Debian by Viktor Radnai and Paul Brossier. A big thanks to them. I added speed change by small steps (handy to tune the listening when playing some musical instrument at the same time). The new functions are:<br>
<br>
<dd> - basic keyboard navigation (skip, pause, speed change, etc.), 
<dd> - looping inside a selection, 
<dd> - pressing play button or key during playback return to the begining of the song.<br>
<br>
<dd>Fftscope was crashing Alsaplayer at exit when this scope was not running. This have been fixed and every user is encouraged to upgrade fftscope.<br>
<hr>
<br>
<dt>April 24, 2007
<dd>Alsaplayer 0.99.78 is out. FLAC-1.1.3 and 1.1.4 support is added. FLAC&lt;=1.1.2 is still supported as before.<br>
<hr>
<br>
<dt>February 11, 2007
<dd>Austin Bingham made the initial release (0.3) of the new alsaplayer python extension module.<br>
<br>
<dd>This module has dependencies on the boost and python libraries. The bindings in this module cover the functionality in control.h. More functionality can be added it you want, but this level of functionality must be what you are looking for in most cases.<br>
<br>
<dd>Fftscope 1.0.3 relesed. This is the first release at sourceforge.net of this visualization plugin<br>
<hr>
<br>
<dt>February 10, 2007
<dd>Alsaplayer have migrated from cvs to svn. The cvs depository will not been updated and will be closed in a few days. See the <a href="svn.php">SVN access page</a> for more.<br>
<hr>
<br>
<dt>February 6th, 2007
<dd>Alsaplayer 0.99.77 released! This is a long wanted bugfix release. Same changes as in the last beta realease.<br>
<hr>
<br>
<dt>February 3rd, 2007
<dd>A new beta release is here, on the left.<br>
<br>
<dd>Changes since version 0.99.76:<br>
<br>
<dd>Some important and long wanted bug fixes:<br>
<dd> - fixes to the "work in progress" gtk2 interface to get it to compile and the --enable-gtk2 configure flag to work,<br>
<dd> many fixes committed by Hubert Chan from Debian. They include patches from him and other peoples, and even a new man page from Debian. A big applaud to them!<br>
<dd> - fixes in the gtk interface, the alsa output plugin, the cdda (cdrom) input plugin, the text interface, correct duration in the display when playing mono files, the flac and audiofile input plugins, the jack output.<br>
<br>
<dd>Every one is encouraged to use this release even if it is beta, because it include important security fixes.<br>
<br>
See the <a href="changelog.php3">ChangeLog</a> for more information.<br>
<hr>
<br>
<dt>February 2nd, 2007
<dd>Me, Dominique Michel, joined the project team as new administrator. The cvs is working again: I applied some long wanted bug fixes and security patches on the cvs. A new release will come soon.<br>
<br>
<dt>Help wanted
<dd>If you want to help the development of the alsaplayer with anything from bug repports to contributing code, feel free to talk on the <a href="lists.php3"> alsaplayer-devel email list</a>.<br>
<hr>
<br>
<dt>June 7th, 2004
<dd>The AlsaPlayer site was offline for a couple of days. I'm in the process of bringing it back up and updating...<br>
<hr>
<br>
<dt>May 2nd, 2003
<dd>Wrote a JACK input plugin. <a href="jack_input-0.1.tar.bz2">Download here</a>. Feed output from any JACK application to AlsaPlayer, including recording sources like line-in and mic!<br>
<hr>
<br>
<dt>April 29th, 2003
<dd>AlsaPlayer 0.99.75 released! This is a bugfix release. See the <a href="changelog.php3">ChangeLog</a> for all the juicy details.<br>
<hr>
<br>
<dt>February 8th, 2003
<dd>AlsaPlayer 0.9.74 is out! This release has many new features including Icecast/Shoutcast support, CDDB lookup support and lots of other fixes. Check out the <a href="changelog.php3">ChangeLog</a>.<br>
<hr>
<br>
<dt>January 24th, 2003
<dd>A new "Related projects" section is available where we list other cool projects related to alsaplayer. A new song of the week, <a href="http://www.eslmusic.com/index.asp">Thievery Corporation rulez!</a>. New release imminent...<br>
<hr>
<br>
<dt>December 1st, 2002
<dd>AlsaPlayer 0.99.73 released. This release has better support for CDDA (CD) audio playback. Some bugs were fixed. <a href="changelog.php3">ChangeLog</a> for details.<br>
<hr>
<br>
<dt>September 18th, 2002
<dd>AlsaPlayer 0.99.72 released. Bug fix release, preparing for glib 2.0 switch.
<hr>
<br>
<dt>June 24th, 2002
<dd>AlsaPlayer 0.99.71 released. Again quite some bug fixes and some minor feature additions. See the
<a href="changelog.php3">ChangeLog</a> for details.<br>
<hr>
<br>
<dt>June 2nd, 2002
<dd>Added information about the Nebulus OpenGL plugin. See the <a href="scopes.php3">Scopes</a> section.<br>
<hr>
<br>
<dt>May 26th, 2002
<dd><a href="/ac3play.php3">AC3Play</a> bugfix release.<br>
<hr>
<br>
<dt>May 16th, 2002
<dd>AlsaPlayer 0.99.70 is out. Lots of bug fixes, brandnew libalsaplayer API,
new FLAC input plugin, new JACK output plugin. XING header parsing, etc.<br>
<hr>
<br>
<dt>May 9th, 2002
<dd>An RPM for RedHat 7.2 is now available on the download page. Thanks to "Angles".<br>
<hr>
<br>
<dt>May 2nd, 2002
<dd>FFTscope was updated to 1.0.1, now requires AlsaPlayer 0.99.60 or higher<br>
<hr>
<br>
<dt>May 2nd, 2002
<dd>If you ever felt the urge to donate money for the purpose of
supporting alsaplayer development, here's your chance!
I added a link to my Paypal account at the bottom of the navigation strip
(left). Donate any amount you wish, $10 or more and you'll get an honorary mention! Go on! ;-)<br>
<br>

</dl>
