<?php

include 'latest_version.php';

?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- alsaplayer standard header -->

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>AlsaPlayer</title>
<link rel="icon" type="image/x-icon" href="favicon.png">
<link rel="stylesheet" type="text/css" media="screen, projection" id="css" href="<?php echo $url; ?>style.css" />
<meta name="GENERATOR" content="vim" />
</head>
<body>

<table>
<caption><img id="logo" src="styles/TrinineBW/Bandeau_gris.png" alt="Logo" /></caption>
<tr>
<!-- sidebar -->
<?php

include 'header_content.inc';

?>
